### ISSUE TITLE
Change default branch from master to main

### ISSUE THREAD

**Issue by sarahzinger** [grafana/x-ray-datasource#102]

**Comment by yaelleC** [comment]
Done (following [this](https://github.com/StevenMMortimer/master-to-main)), `main` is now the default branch.
However, I can't seem to remove `master` just yet as one PR (https://github.com/grafana/x-ray-datasource/pull/93) depends on it. I'll check out `[aocenas/trace-to-logs](https://github.com/grafana/x-ray-datasource/tree/aocenas/trace-to-logs)` see if I can fix that

**Comment by yaelleC** [comment]
Manually updated the base branch for #93 and removed `master`. 
Closing this issue
