### ISSUE TITLE
Minimal IAM role doesn't include permissions for the service map

### ISSUE THREAD

**Issue by jangaraj** [grafana/x-ray-datasource#108]
Could you include permissions for the service map into minimal IAM role, please? It looks like `xray:GetServiceGraph` is not enough.

Thank you.

**Comment by iwysiu** [comment]
Hi @jangaraj ! The minimal policy for x-ray can be found here: https://github.com/grafana/x-ray-datasource#iam-policies

**Comment by jangaraj** [comment]
@iwysiu Yes, but when you used that minimal policy from the doc/readme, then you will get 403 when you will try to show service map.

**Comment by iwysiu** [comment]
Sorry, I misunderstood. I'll add it to the documentation. Though when I tested it, adding `xray:GetServiceGraph` was enough for service map. Did that not work for you?

**Comment by jangaraj** [comment]
`xray:GetServiceGraph` wasn't enough. I used lazy approach `xray:Get*`, but it will be fine if all permissions will be listed explicitly.

**Comment by jangaraj** [comment]
`xray:GetServiceGraph` wasn't enough. I used lazy approach `xray:Get*`, but it will be fine if all permissions will be listed explicitly.
