### ISSUE TITLE
X-Ray Documentation Is Missing an IAM Permission for ServiceMaps

### ISSUE THREAD

**Issue by anybodysguest** [grafana/x-ray-datasource#123]
**What happened**:
The following page lists out a number of IAM actions that must be permitted in order to use the X-Ray datasource correctly.

https://grafana.com/grafana/plugins/grafana-x-ray-datasource/

In my testing I found that a 403 error was being thrown when trying to access the ServiceMap.

**What you expected to happen**:
After provisioning my IAM role based on the documentation shown in the Overview section, I should be able to access the ServiceMap.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an IAM role based on the current documentation.
2. In Grafana create an X-Ray data source that assumes this role.
3. In the query pane, select the "**Service Map**" query type.
4. Click on the **Query** Inspector button.
5. Click **Refresh**

You should get the following error: "**AccessDeniedException: status code: 403, request id:...**"

**How I Resolved the Issue**:
I added  the "**xray:GetServiceGraph**" to the action list in the documentation.  So, the list should read:

{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "xray:BatchGetTraces",
        "xray:GetTraceSummaries",
        "xray:GetTraceGraph",
        "xray:GetGroups",
        "xray:GetTimeSeriesServiceStatistics",
        "xray:GetInsightSummaries",
        "xray:GetInsight",
        **"xray:GetServiceGraph",**
        "ec2:DescribeRegions"
      ],
      "Resource": "*"
    }
  ]
}

**Anything else we need to know?**:
Please update the Overview page so that the list of required IAM actions includes "x**ray:GetServiceGraph**".

https://grafana.com/grafana/plugins/grafana-x-ray-datasource/

**Environment**: Linux Container running in AWS Fargate
- Grafana version:  8.5.3
- Plugin version: 1.4.0
- OS Grafana is installed on: Linux(AWS Fargate Distro)
- User OS & Browser: Mac/Chrome
- Others:

**Comment by fridgepoet** [comment]
Thanks @anybodysguest!

I confirmed this issue
* Grafana version: `main` 9.0.0-pre
* Plugin version: `main` 1.4.0
