### ISSUE TITLE
X-Ray Datasource Failed to Load Regions

### ISSUE THREAD

**Issue by nutslove** [grafana/x-ray-datasource#135]
Hi,

I’m using Grafana v9.1.1 and installed X-Ray datasource v2.0.1 with Access & secret key OR Credentials file.
Every time I choose X-Ray at Explore or Dashboard, a warning about the region is showing.
Is there any workaround for this?
Thanks.
![image](https://user-images.githubusercontent.com/43600385/189028869-5807d625-9709-4fa2-94f4-16eb25162e1d.png)
![image](https://user-images.githubusercontent.com/43600385/189028882-74757ba2-4fb4-4375-9f43-bec4a4e73e8e.png)

※grafana log related this issue(I think)
`"logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-09-08T02:25:51.251461521Z level=error msg=\"Request Completed\" method=GET path=/api/datasources/74/resources//regions status=500 remote_addr=100.116.23.7 time_ms=66 duration=66.630859ms size=140 referer=\"http://10.47.58.169:8083/explore?left=%7B%22datasource%22%3A%22UEChu2M4z%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D&orgId=1\" traceID=00000000000000000000000000000000\n"`

`"logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-09-08T03:26:22.569261874Z level=error msg=\"Request Completed\" method=GET path=/api/datasources/74/resources//regions status=500 remote_addr=100.116.28.51 time_ms=115 duration=115.425857ms size=140 referer=\"http://10.47.58.169:8083/explore?left=%7B%22datasource%22%3A%22qD2SVdQ7k%22%2C%22queries%22%3A%5B%7B%22refId%22%3A%22A%22%2C%22queryType%22%3A%22getTraceSummaries%22%2C%22query%22%3A%22%22%2C%22group%22%3A%7B%22FilterExpression%22%3Anull%2C%22GroupARN%22%3A%22arn%3Aaws%3Axray%3Aap-northeast-1%3A154409968892%3Agroup%2FDefault%22%2C%22GroupName%22%3A%22Default%22%2C%22InsightsConfiguration%22%3A%7B%22InsightsEnabled%22%3Afalse%2C%22NotificationsEnabled%22%3Afalse%7D%7D%2C%22region%22%3A%22default%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-1h%22%2C%22to%22%3A%22now%22%7D%7D&orgId=1\" traceID=00000000000000000000000000000000\n"`

**Comment by sunker** [comment]
@nutslove currently the X-Ray plugin is using the `ec2:DescribeRegions` api to list regions. Can you verify the role or user that is running the X-Ray plugin has this permission? 

FYI, for currently looking into alternative ways of loading regions, and hopefully there should be no need for the `ec2:DescribeRegions` permission in the future.

**Comment by nutslove** [comment]
@sunker Thank you for the reply.
It was gone after attaching a policy including `ec2:DescribeRegions` to the user who has permission!
I appreciate your help!
