### ISSUE TITLE
Xray Trace does not show SQL on trace in grafana

### ISSUE THREAD

**Issue by mesparks** [grafana/x-ray-datasource#142]
**What happened**:
* XRAY trace in AWS shows SQL on trace, when viewing it in grafana it does not show it

**What you expected to happen**:
* I expect to see SQL in the trace

**How to reproduce it (as minimally and precisely as possible)**:
* Configure java otel collector to send xray traces to xray
* Configure XRAY datasource
* Look at traces in grafana

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.7
- Plugin version: 1.4.0
- OS Grafana is installed on: Managed Service from AWS
- User OS & Browser: MacOS / Chrome
- Others:

**Comment by sarahzinger** [comment]
@mesparks can you maybe show a screenshot of what you are seeing in the aws console that you do not see in grafana? I'm not sure what you mean by "sql on trace"

**Comment by mesparks** [comment]
XRAY in AWS <- SQL is there
![Screen Shot 2022-10-20 at 11 23 11 AM](https://user-images.githubusercontent.com/57384779/197017267-5d812e42-4bbd-4322-aa80-9d8db1c9f5dd.png)

Grafana Xray Trace <- NO SQL
![Screen Shot 2022-10-20 at 11 26 48 AM](https://user-images.githubusercontent.com/57384779/197017691-651a1d3f-0ed7-4030-a4c6-69f8699c36ae.png)

**Comment by sunker** [comment]
Thanks for getting back to us @mesparks. Will discuss this with the team and report back to you.

**Comment by sarahzinger** [comment]
Hi @mesparks it looks to me like this SQL feature is a "subsegment". My understanding is that any segment and subsegment data we recieve from aws we forward on to the user. It seems likely to me that this information is not being returned in the public api so there is no way for grafana to render it. 

But if you are able to make a specific public api call for this data, do let us know and we can see if we are somehow accidentally filtering this information somehow, or if there's a way for us to ping directly for it.
