### ISSUE TITLE
404 Not Found Instantiating

### ISSUE THREAD

**Issue by alex-souslik-hs** [grafana/x-ray-datasource#149]
**What happened**:
Existing x-ray-datasource stopped working, showing the following error instead of the data.
```
Fetch error: 404 Not Found Instantiating https://grafana.some.domain/public/plugins/grafana-x-ray-datasource/module.js Loading plugins/grafana-x-ray-datasource/module
```
**What you expected to happen**:
Seeing my x-rya traces etc.
**How to reproduce it (as minimally and precisely as possible)**:
Try to create a datasource with the plugin

**Screenshots**

![screenshot](https://user-images.githubusercontent.com/106610853/200582819-d00c7ad9-89f5-4700-aa2f-7bde17b0f3e4.png)
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.1
- Plugin version: 2.1.2
- OS Grafana is installed on: official docker container on k8s
- User OS & Browser: macOS, Firefox
- Others:

**Comment by kevinwcyu** [comment]
Hi @alex-souslik-hs, I tried running the same Grafana version and plugin version in docker, but was not able to reproduce this.

I have some questions: Are you using any other data sources, and if so, does this happen with them as well? Have you tried restarting the Grafana instance?

The 404 error makes me think it's not an X-Ray data source specific issue though.

**Comment by kevinwcyu** [comment]
Hi @alex-souslik-hs, thanks for the info.

Can you check the logs to see if there are any messages about the x-ray-datasource? https://grafana.com/docs/grafana/latest/troubleshooting/#troubleshoot-with-logs
