### ISSUE TITLE
Get regions for ConfigEditor from backend

### ISSUE THREAD

**Issue by iwysiu** [grafana/x-ray-datasource#152]
Currently, the [ConfigEditor](https://github.com/grafana/x-ray-datasource/blob/main/src/components/ConfigEditor/ConfigEditor.tsx) uses a hardcoded list for its regions. Instead, it should behave similarly to [Cloudwatch](https://github.com/grafana/grafana/blob/000b4f878d5265594437dbffa2acc4ac193f99f0/public/app/plugins/datasource/cloudwatch/components/ConfigEditor.tsx), saving the datasource and calling the backend to get the regions. This will mean that we don't have to update [regions.ts](https://github.com/grafana/x-ray-datasource/blob/main/src/components/ConfigEditor/regions.ts) when the available regions change.

**Comment by fridgepoet** [comment]
Let us know if you want us to look into this!
