### ISSUE TITLE
Alerts are not working in Amazon Managed Grafana

### ISSUE THREAD

**Issue by shahriarbro** [grafana/x-ray-datasource#194]
I'm struggling  to use X-Ray datasource for Alerting.
Based on [Amazon Documents](https://docs.aws.amazon.com/grafana/latest/userguide/v9-alerting-explore-numeric.html) the table response returned to Grafana from the query should includes **only one** numeric  column. 
As all the query responses to X-Ray return multiple number columns, no alerts can be defined and I constantly getting 

"Failed to evaluate queries and expressions: input data must be a wide series but got type not (input refid)"

 
Example:

1. Go to "Alert Rules"
2. Click on 'Create Alert Rules'
3. Add a query with AWS X-Ray datasource

![image](https://github.com/grafana/x-ray-datasource/assets/131158764/7c7a08d1-cb79-4739-bb5e-ecad7c28cca5)

**Environment**:
- Grafana version: 9.4
- Plugin version: 2.6.1
- OS Grafana is installed on: Amazon Managed Grafana

**Comment by iwysiu** [comment]
Hi @shahriarbro ! Are you sure you want to do a Trace List query? I suspect that you may want to do a Trace Statistics query, in which case you can use the Columns field to get just the column that you want to alert on.
![Screenshot 2023-08-16 at 4 58 51 PM](https://github.com/grafana/x-ray-datasource/assets/5421859/fb8d3be4-585a-4560-9707-4be10180a8b6)

If you did want to do a Trace List query, I don't think alerting is supported for them, unfortunately.

**Comment by shahriarbro** [comment]
Thanks @iwysiu for the help!
