### ISSUE TITLE
JS error after Summaries query columns changed

### ISSUE THREAD

**Issue by davkal** [grafana/x-ray-datasource#26]
0.  Explore with xray datasource
1. Select Trace Statistics as type and set query runner to 10s repeat
2. When a full graph appears, set Columns to render only a single column and then hover over the existing graph (before the next query run happens)
3. When next automatic query run returns, an error is shown:

<img width="1309" alt="Screenshot 2020-08-13 at 11 05 05" src="https://user-images.githubusercontent.com/859729/90124849-f4ac1400-dd58-11ea-8ee3-4891acc3617d.png">

**Comment by zoltanbedi** [comment]
I was able to reproduce this in 1.3.3.

**Comment by asimpson** [comment]
I am unable to reproduce this running version 1.3.3. of the X-Ray plugin and Grafana 8.5.0/Grafana 8.2.5. I can re-produce this running Grafana 7.5.7 and 1.3.3 of the plugin. The solution seems to be to upgrade to Grafana 8.
