### ISSUE TITLE
Is assumeRoleArn supposed to work?

### ISSUE THREAD

**Issue by andreafalzetti** [grafana/x-ray-datasource#62]
I have tried to use this plugin but assume role auth but I cannot get it to work. I use the same approach for CloudWatch and it works fine.

I set the IAM permissions as specifided in the readme.

I managed to make it work with AWS access key credentials however.

I am wondering if this method was implemented at all?

```
t=2021-01-21T17:35:59+0000 lvl=dbug msg=CreateXrayClient logger=plugins.backend pluginId=grafana-x-ray-datasource userAgent="aws-sdk-go/1.35.30 (go1.15.1; linux) Grafana/7.3.6"
t=2021-01-21T17:35:59+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="Failed to check plugin health: Health check failed" remote_addr=xxxxx
t=2021-01-21T17:35:59+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/4/health status=500 remote_addr=xxxxxx time_ms=4 size=40 referer=https://example.com/datasources/edit/4/
```

**Comment by zoltanbedi** [comment]
Hi @andreafalzetti,
You are right it is not used. We will fix this soon.

**Comment by aocenas** [comment]
@andreafalzetti which version of the plugin do you use? We changed the auth logic to use a common SDK so since version 1.2 it should work the same way in every aws plugin.

**Comment by zoltanbedi** [comment]
Sorry I reacted too fast. Thing is that it is using assumeRoleArn but I couldn't find it in this repository because as Andrej mentioned it is used in the https://github.com/grafana/grafana-aws-sdk also cloudwatch doesn't uses the sdk yet thats why I saw it using there.

**Comment by andreafalzetti** [comment]
I build Grafana using Docker and install the latest version of the plugin all the time, I believe now it's 1.2.0.

I have tried more but I keep getting the same error. I am also using the CloudWatch datasource with success, and I have extended the IAM role with another policy for the XRAY/EC2 permissions as listed in the readme of this project without any luck in fetching data via the assume role.

I even tried attaching the Administrator policy with full access to AWS to see if the issue is related to IAM blocking a specific request made but it's not the case.

I suspect there is somewhere in the plugin an issue with the assume role. Can you recommend a way to debug it?

Thanks @zoltanbedi @aocenas 🙏

**Comment by aocenas** [comment]
@ryantxu or @wbrowne Do you track anything like this in the https://github.com/grafana/grafana-aws-sdk? I would assume some other projects using it would have already reported this.

**Comment by ryantxu** [comment]
We should absolutely add any fix/change to the shared repo -- cc @sunker

**Comment by sunker** [comment]
I haven't had time to look into the grafana-aws-sdk that much yet, but by taking a quick glance at the code is seems like ARN support is [implemented](AssumeRoleARN).

**Comment by aocenas** [comment]
@sunker yeah the code handling it seems to be there but honestly not sure how to test it quickly. That's why I was thinking if there isn't existing issue or report, would save some time :D

**Comment by aocenas** [comment]
btw @sunker as far as was searching cloudWatch doesn't use the `grafana-aws-sdk` yet right? So it would make sense that the behaviour could be different there and in any plugin using the sdk.

**Comment by andreafalzetti** [comment]
this might sound stupid as I am not familiar with the codebase, but I noticed that in grafana-aws-sdk is defined as [assumeRoleARN](https://github.com/grafana/grafana-aws-sdk/blob/f1b638488d10927dcd58e7715c0a82224fd6e704/pkg/awsds/settings.go#L69), here instead it's used as [assumeRoleArn](https://github.com/grafana/x-ray-datasource/blob/ab92bd02a1dc69d87dd080e93f79074a235600d8/src/components/ConfigEditor/types.ts#L13). Could this be the reason @aocenas?

**Comment by sunker** [comment]
> btw @sunker as far as was searching cloudWatch doesn't use the `grafana-aws-sdk` yet right? So it would make sense that the behaviour could be different there and in any plugin using the sdk.

Correct! We plan to use the grafana-aws-sdk eventually, but there's a few things that we need to be sorted out first. You can follow the discussion [here](https://github.com/grafana/grafana/pull/29550)

**Comment by sunker** [comment]
> @sunker yeah the code handling it seems to be there but honestly not sure how to test it quickly. That's why I was thinking if there isn't existing issue or report, would save some time :D

Yean I'm afraid I don't know how to test this either. I haven't really touched to auth code in Cloudwatch, but hopefully I'll have time to do that soon. Might be able to help you test this after that.

**Comment by andreafalzetti** [comment]
@sunker did you see my comment about the lowercase vs uppercase difference? Any thought?

**Comment by aocenas** [comment]
@andreafalzetti ah you are probably right :facepalm:. Let me do a quick PR. Would you be able to test if from a PR branch? Would probably speed this up a bit.

**Comment by aocenas** [comment]
Ok interestingly the wrong casing does not seem to be the problem (seems Go unmarshal is not case sensitive https://golang.org/pkg/encoding/json/#Unmarshal), the role seems to be correctly propagated and I can see a correct role logged here https://github.com/grafana/grafana-aws-sdk/blob/main/pkg/awsds/sessions.go#L123.

**Comment by andreafalzetti** [comment]
I am sorry this was a misconfiguration which I finally spotted. I added all the right IAM permissions, but at the same time, there was an explicit deny for EC2 stuff in the same role 🤦
