### ISSUE TITLE
Version 1.3.0 Regression on Docker fails  

### ISSUE THREAD

**Issue by yossicohn-hs** [grafana/x-ray-datasource#66]
Steps:
1. Run Docker
docker run --name gf-1.3  -d -p 3006:3000 -e "GF_INSTALL_PLUGINS=grafana-x-ray-datasource" -v grafana-otel:/var/lib/grafana -v /Users/<Your User Name>/credentials:/usr/share/grafana/.aws/credentials  grafana/grafana
Getting error over /datasources/edit/1/:
`(intermediate value).setConfigEditor(...).setQueryEditorHelp is not a function Evaluating http://localhost:3007/public/plugins/grafana-x-ray-datasource/module.js Loading plugins/grafana-x-ray-datasource/module`

2. Run Docker
docker run --name gf-1.2  -d -p 3006:3000 -e "GF_INSTALL_PLUGINS=grafana-x-ray-datasource 1.2.0" -v grafana-otel:/var/lib/grafana -v /Users/<Your User Name>/credentials:/usr/share/grafana/.aws/credentials  grafana/grafana
works properly

**Comment by zoltanbedi** [comment]
Hi @yossicohn-hs,
Thanks for reporting this. Yes it seems like that we broke backwards compatibility accidentally so 1.3.0 is only compatible with  Grafana 7.4.0-beta1. Sorry about that we will fix this.
