### ISSUE TITLE
IAM Role Switching

### ISSUE THREAD

**Issue by detrek77** [grafana/x-ray-datasource#71]
Hello,

My team is looking to take advantage of this plugin as we have made a pretty heavy push towards xray in the last few months. I noticed the disclaimer that IAM Role Switching is not supported at this time. 

Is there any timeline around when this feature might be added to the plugin? Or maybe a roadmap?

Thanks!

**Comment by aocenas** [comment]
Hey @detrek77 sorry for late reply. From some version we allow to specify a role to assume, you just put the Role Arn during configuration and that role will be used to do all the API access. I think we should remove that disclaimer. Or do you have in mind some other feature or different way how this should work?

**Comment by ivanahuckova** [comment]
Closing this issue as there wasn't any response.
