### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by jordanpurinton** [grafana/x-ray-datasource#75]
When trying to open up an X-Ray trace from a trace list in a split panel view, all I’m getting is Cannot read property 'id' of undefined. I'm able to query data using the trace list, but any time I try and click on a trace, a tab opens to the explore page, showing this error. I would expect this to open up a split pane view as described by the docs, but it is not.

Can someone help me out here?

**Grafana Version** - 7.3.4

<img width="793" alt="Screen Shot 2021-03-19 at 3 13 16 PM" src="https://user-images.githubusercontent.com/12102971/112029969-2582d180-8b10-11eb-8eda-971a3cafebb9.png">

**Comment by zoltanbedi** [comment]
The plugin from version 1.3.0 is only works with Grafana 7.4 and above. You should upgrade your Grafana or you need to go back to version 1.2.0

**Comment by jordanpurinton** [comment]
OK, I'll do that. Will close this out then.
