### ISSUE TITLE
Lookup by Trace ID returns an error

### ISSUE THREAD

**Issue by camsellem** [grafana/x-ray-datasource#83]
From a prospect:

As far as I can see the X-Ray plugin search by trace id is also broken. This breaks when you want to do a lookup by trace id but also break all internal links inside the app. So for example if you run a search for traces then click one of them it fails with the same message.

Prospect is on Grafana 8.0.4

https://user-images.githubusercontent.com/3879044/126638181-c12400e8-0c92-4283-8c84-cddf2ea41b33.mov

**Comment by Elfo404** [comment]
Hi @camsellem , is Grafana running on AMG or is it installed on a custom machine? also, do you know which exact version of plugin is it installed?

**Comment by camsellem** [comment]
Hi - it's a custom machine (EC2 instance) and plugin version is grafana-x-ray-datasource @ 1.3.4

Although looks like the prospect has spotted the issue. See thread below.

![image](https://user-images.githubusercontent.com/3879044/126728372-32b50985-c9cd-4083-b4b1-14d857ffdd4d.png)

![image](https://user-images.githubusercontent.com/3879044/126728377-4ccda134-4cf1-4cbc-827e-19bd4544f30b.png)

**Comment by aocenas** [comment]
hmm yes seems like we are trying to get a hostname from the url which fails if it's not a full url.
