### ISSUE TITLE
Across account access using x-ray-datasource

### ISSUE THREAD

**Issue by sahilsapolia** [grafana/x-ray-datasource#90]
Hi,

I am working on adding X-ray datasource in Grafana for a different AWS account. I have enabled the Grafana AWS role to assume a role on second AWS account but I am not having any luck getting it configured.

Do we know. if this is supported as of today.

My used case is. I am collecting X-ray traces in individual account and want to centralize the dashboards on Grafana. 

Thanks

**Comment by sarahzinger** [comment]
@sahilsapolia I'm sorry for the delay! Just looking at this ticket now.

Yes, we do support assuming a role with AWS. Are you still running into this issue? If so, perhaps you can give us some more repro steps like what version of grafana and what version of xray you're on?

**Comment by jangaraj** [comment]
I don't have a problem with cross accoun access, so I bet your cross accoun role is not configured properly. See https://community.grafana.com/t/aws-cloudwatch-datasource-with-an-assumed-iam-role/8011/4 - just use actions from the https://github.com/grafana/x-ray-datasource readme.

**Comment by sunker** [comment]
@sahilsapolia I'll close this issue now. Please feel free to reopen if you need to. If you have questions on how to configure assume roles, please refer to AWS' [documentation](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) or our [community site](https://community.grafana.com/).
