### ISSUE TITLE
No releases that works in grafana running on ARM (garaviton instances)

### ISSUE THREAD

**Issue by sudhirpandey** [grafana/x-ray-datasource#92]
Hi
We are building grafana images with plugins installed as part of docker build process.
With this plugin enabled(installed) build works fine for amd64 images.

But for Arm64 based docker images we cannot build because grafana fails to find the plugin for the very architecture. Is it possible to produced and distribute the zip file for arm images too.

Error we get while installing the plugin in grafana arm64 is 
#21 7.652 
#21 8.933 Error: ��� grafana-x-ray-datasource v is not supported on your system (Grafana v8.2.3 linux-arm64)

**Comment by sarahzinger** [comment]
@sudhirpandey sorry for the delay, just looking at this now, and I'm curious if you still run into this issue?

**Comment by fridgepoet** [comment]
There are no builds yet for arm64. 
This can be reproduced on an arm machine with grafana-cli 
``` 
./grafana-cli --pluginsDir "{plugins dir path}" plugins install grafana-x-ray-datasource       
Error: ✗ grafana-x-ray-datasource v is not supported on your system (Grafana v8.4.0-pre darwin-arm64)
```

and there are no releases for arm64 available https://github.com/grafana/x-ray-datasource/releases

**Comment by fridgepoet** [comment]
Thanks for raising the issue @sudhirpandey, I've just tested and it should be ok now with v1.4.0
