### ISSUE TITLE
Add links to logs from a span

### ISSUE THREAD

**Issue by aocenas** [grafana/x-ray-datasource#94]
Add link to logs, based on configured linked ClouWatch data source. Similar to linking between Tempo and Loki

**Comment by sarahzinger** [comment]
Just adding this to the data sources board, to ensure we keep track of it, but it sounds like the plan is for @aocenas to finish this up once he has the log group info he needs. Let me know if you want a code review or anything!

**Comment by sunker** [comment]
@sarahzinger is this waiting for something or can it be moved to the backlog?

**Comment by sarahzinger** [comment]
I suppose we can move it to the backlog, I'm still working on getting the right test app set up to properly test this.

**Comment by sarahzinger** [comment]
Just an update on this:

I looked at this, was able to create better test trace data with corresponding log groups and I don't think this will work for anything other than Lambdas as we don't really have a way to know the log group name for services besides lambdas. We thought ECS and EKS would follow a similar pattern, but it seems that log group names are case sensitive, which at least in the [test app](https://catalog.workshops.aws/observability/en-US) we created it seems that the service names passed in subsegments often are all lowercase, even if the service name is case-sensitive.


I think we have a few possibilities here:
- merge this pr as is and only support lambdas
- see if AWS can append associated cloudwatch log group names to subsegments or traces
- see if AWS can create a way to query across all cloudwatch log groups for logs containing one x-ray trace id and expose it in the sdk
- or possibly saying this feature will not be supported for the time being. 

Will discuss with the AWS team to see if they also have ideas we may have not considered.

**Comment by yagrxu** [comment]
I think the "Span to Logs link" should support data source selection (Loki, CloudWatch Logs or external links, similar as Derived fields in Loki data source configuration).
I am using loki with AWS managed Grafana and AWS managed Prometheus. In this case I should be able to jump from X-Ray trace view to my loki with query (almost the same as tempo features)

**Comment by katebrenner** [comment]
closing as stale
